language: node_js
node_js:
- '7.6'

before_script:
- npm install

script:
- npm test

after_success: bash ./bin/deploy.sh

env:
  global:
  - GIT_USER: Travis CI
  - GIT_EMAIL: miya0001@users.noreply.github.com
  - GH_REF: github.com/ogijima-library/wmap
  - secure: "NiYgdIv27wh/MaJjSByAjCI0t05Gnlonp3u8QJnD8k8cZ3SwF38MOHoW4dV8Qr1hJ5zGzPttMAJuM3U6OLE1D7k/qOtRYQdtSws5kIaPjLulAgcMNsD9Bs6ZLqvqtMPSZVXNhnxghkMrhcWWK0vjEATgIJrXL6DvXO1N0a+H4xHcVjDx+tQLOoCwtn5BjYZQY+SzTXjh1SwVuXRO0J6N65+3upD0xQNtlj7GhEekplKFMz1l98VuEqP9E/Uaj0ILRyeM6kJTHplUFNatZHY0VUFXQX45X0Y6GjjMlRbrk1BHFF/1OlWAdiHoQIwEfM2YaD+5YSDNWRzdDWAGdxKRT9qNGRvXAAmNVwsx6LrMAtYFWCYYB1LyxUeLkbllOH7kYy9Po2jAGzsqld/Fta4Xdjdxt7Tz3+dd6AZnL/XtjpVnC8zyco1nUxh3LoZ+NrCmp/8/TAwuhHmDpGWocUx482wyPsk22BRfVBxGrTUc0N2QueT+ISaZqBzm5VxFj7z2BV9Ta23dVyFAKGogMIUCPM7tNAOJPCrj5IZGv4afrd+efhwcjGnVLIqW2Ezk10kZcgn4CYRumu0+KbragafZqDpyFwbJv8XTj18DUiS+SNkJx8oNXqrISrqmzGGyLn8tAC/1H5RsGZZxoIumbzHDlX28xy8wmWcG2k/xvW4ED1c="
